

# Permalinks
permalink:        pretty

# Setup
title:            "Kanónes User Guide"
tagline:          'Build corpus-specific parsers for ancient Greek'
description:      ''
baseurl: '/kanones/'

links:
  - title:  Github repository
    url:  https://github.com/neelsmith/tabulae
    external: true
